#开发环境
dev: 
  server:
    port: 7001
dev:    
  spring:
    application:
      name: consumer
dev:      
  eureka:
    client:
      service-url:
        defaultZone: http://server1:8001/eureka/
dev:        
  feign:
    hystrix:
      enabled: true
dev:      
  applicaton:
    profiles: dev
