#测试环境
server:
  port: 7001
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
feign:
  hystrix:
    enabled: true
applicaton:
  profiles: test